# {{ $PACKAGE_TITLE }}

[![{{ $PACKAGE_TITLE }}](https://banners-laravel-ready.vercel.app/{{ urlencode($PACKAGE_TITLE) }}.png?theme=light&packageManager=composer+require&packageName={{ urlencode($COMPOSER_PACKAGE_NAME) }}&pattern=architect&style=style_1&description=By+{{ urlencode($VENDOR_NAMESPACE) }}&md=1&showWatermark=1&watermarkText=generated+by+laravel-ready\/packager&fontSize=100px&images=https%3A%2F%2Flaravel.com%2Fimg%2Flogomark.min.svg?brand=laravel)]({{ $REPO_URL }})

[![Stable Version][badge_stable]][link_packagist]
[![Unstable Version][badge_unstable]][link_packagist]
[![Total Downloads][badge_downloads]][link_packagist]
[![License][badge_license]][link_license]

## 📂 About
@if($PACKAGE_DESC)
{{ $PACKAGE_DESC }}...
@endif

## 📦 Installation

Get via composer

```bash
composer require {{ $COMPOSER_PACKAGE_NAME }}
```

@if ($SETUP_CONFIG)
## ⚙️ Configs

```bash
php artisan vendor:publish --tag={{ $PACKAGE_SLUG }}-config
```@endif

@if ($SETUP_DATABASE)
## 📅 Migrations

```bash
# publish migrations
php artisan vendor:publish --tag={{ $PACKAGE_SLUG }}-migrations

# apply migrations
php artisan migrate --path=/database/migrations/{{ $VENDOR_SLUG }}/{{ $PACKAGE_SLUG }}
```
@endif

## ⚓Credits

- This project was generated by the **[packager](https://github.com/laravel-ready/packager)**.

[badge_downloads]: https://img.shields.io/packagist/dt/{{ $COMPOSER_PACKAGE_NAME }}.svg?style=flat-square

[badge_license]: https://img.shields.io/packagist/l/{{ $COMPOSER_PACKAGE_NAME }}.svg?style=flat-square

[badge_stable]: https://img.shields.io/github/v/release/{{ $COMPOSER_PACKAGE_NAME }}?label=stable&style=flat-square

[badge_unstable]: https://img.shields.io/badge/unstable-dev--main-orange?style=flat-square

[link_license]: LICENSE

[link_packagist]: https://packagist.org/packages/{{ $COMPOSER_PACKAGE_NAME }}
