<!-- This file was generated by laravel-ready/packager and don't edit it manually. -->

# Packager Notes

This folder contains the generated packages with the packager.


## Loading local packages

### Step 1: Add repository path

In the [composer.json](../composer.json) file, we define the following "repositories" at the root level. We need to tell you where the package is.

```json
...
// add this code block if not exists
"repositories": [
    {
        "type": "path",
        "url": "./packages/<package-folder-name>"
    }
],
...
```

### Step 2: Add package for autoload

We add the package manually for autoloading then the composer loads PHP files from this source.

```json
...
// add this code block if not exists
"autoload": {
    "psr-4": {
        "App\\": "app/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/",
		"PackageVendor\\PackageNamespace\\": "./packages/<package-folder-name>/src" <-- add this line
    }
},
...
```

### Step 3: Install local package

In terminal, run the following command:

```bash
composer require package-vendor/package-name
```
